### ISSUE TITLE
Anzahl der Eis-Menge am Eis-Button anzeigen

### ISSUE THREAD

**Issue by JulianSchoem** [Fasust/FrozenJoghurtBuilder#18]
Kleine Bubble an die Eis-Bubble packen, bei der dann 1/3 oder so gesetzt wird.

**Comment by JulianSchoem** [comment]
Counter ist im Interface implementiert. Hintergrund Funktionalität fehlt noch.

**Comment by Fasust** [comment]
Interface in Order Hinzugefügt und in Orderprocess Implementiert.
