### ISSUE TITLE
Share Funktionalität - Daten (Name, Rezept & Bild) in die Firebase

### ISSUE THREAD

**Issue by JulianSchoem** [Fasust/FrozenJoghurtBuilder#19]

**Comment by JulianSchoem** [comment]
Die Bestellliste befindet sich nun im order share auch in einem textview. Zusätzlich habe ich ein EditText Feld eingebaut, in das man den Namen eingeben soll. Vielleicht brauchen wir hier noch eine Fehlermeldung, falls man keinen Namen angegeben hat

**Comment by Fasust** [comment]
Textuell Lassen sich Die Daten nun in Firestore Laden.
Ich muss noch die Bild verlinkung einbauen und einen EditText für die Description einbauen.
Zudem muss das Veröffentlichen den User wieder zurück auf die Main Activity Bringen.
