### ISSUE TITLE
Interface: Oder Process Activity: Listitems einrücke und wieder auf den stand des Constraints Layouts bringen

### ISSUE THREAD

**Issue by Fasust** [Fasust/FrozenJoghurtBuilder#21]

**Comment by JulianSchoem** [comment]
ist verbessert.

@Fasust Ich habe zusätzlich in das manifest eingebaut, dass man die App nur im Portrait und nicht mehr im Landscape nutzen kann. Auf meinem Virtual Device hat es nicht geklappt, aber ist im Netz die genutzte Lösung. Probiere es bitte bei dir einmal.
