### ISSUE TITLE
Notification implementieren

### ISSUE THREAD

**Issue by JulianSchoem** [Fasust/FrozenJoghurtBuilder#28]
Task vom Prof vom 14.06.

**Comment by JulianSchoem** [comment]
Ideen: 
Bei Zutaten Änderung
5 neue Rezepte in Gallerie

**Comment by dariola** [comment]
sofern issue sprache ändern unter Einstellungen erfüllt, beschäftige ich mich damit

**Comment by JulianSchoem** [comment]
Id mitgeben beim veröffentlichen. Sobald jemand dann ein Rezept von diesem Nutzer scannt wird dieser benachrichtigt
