### ISSUE TITLE
Sprach Einstellung hinzufügen

### ISSUE THREAD

**Issue by Fasust** [Fasust/FrozenJoghurtBuilder#38]

**Comment by JulianSchoem** [comment]
@dariola Bitte kümmere dich darum, dass im Menü. in dem sich der Link zum Impressum befindet, ein weiterer Link zu einer Settingsseite kommt, auf der man die Sprache der App ändern kann in Englisch/Deutsch.

**Comment by dariola** [comment]
Einstellungen neben Impressum im Popup Menu bereits hinzugefügt, Funktion fehlt

**Comment by Fasust** [comment]
**Unbedingt** Über Prefrences Machen (Vorgabe als Noten Kreterium)

**Comment by Fasust** [comment]
Hab grad mal geschaut. Ist wohl echt nicht so easy. Würde vorschlagen das wir versuchen die Preffrences noch anders ein zu binden.
