### ISSUE TITLE
Order Prozess verbessern

### ISSUE THREAD

**Issue by JulianSchoem** [Fasust/FrozenJoghurtBuilder#49]
Text am Anfang, dass man über die Buttons Zutaten hinzufügen kann

Zeigen dass sich der Preis nicht verändert

**Comment by JulianSchoem** [comment]
@Fasust Ich habe einen Text (id: textView_howToInfo) auf die Order Process gebaut, der nochmal kurz erklärt, was man zutun hat. Dieser verschwindet unter der ersten Zutat sobald sie gesetzt wird. Jedoch sollten wir ihn vielleicht komplett ausblenden, sobald man eine erste Zutat gewählt hat. Kannst du mir in der nächsten Woche zeigen wo ich das abfragen kann?

**Comment by Fasust** [comment]
@JulianSchoem Man kann bei jedem View die "Visibility" Einstellen (Sie Orderprocess Loading Bar)

**Comment by JulianSchoem** [comment]
@Fasust das ist mir klar.. Aber ich brauche die Stelle an der ich schauen kann ob die Liste befüllt ist. Vielleicht finde ich es auch selbst.
