### ISSUE TITLE
In den Preffrences ein Setting anlegen mit denen Man Benachritigungen An und Aus stellen kann

### ISSUE THREAD

**Issue by Fasust** [Fasust/FrozenJoghurtBuilder#52]
Wir müssen Prefrences verwenden.
Dies ist eine einfach Möglichkeit das zu tun

**Comment by JulianSchoem** [comment]
@Fasust Also Sprache wechseln wir nicht mehr? Dann kann @dariola die Sprachsettings ja closen und dieses hier übernehmen, richtig?

**Comment by Fasust** [comment]
richtig


Julian Schoemaker <notifications@github.com> schrieb am Mo., 2. Juli 2018
um 20:31 Uhr:

**Comment by dariola** [comment]
Preferences sind hinzugefügt, Notifications scheint bereits in einer Form vorhanden zu sein, einzelne Settingspreferences werden demnächst angepasst und nicht gebrauchte entfernt
