### ISSUE TITLE
Präsentation vorbereiten 19.07

### ISSUE THREAD

**Issue by Fasust** [Fasust/FrozenJoghurtBuilder#60]

**Comment by JulianSchoem** [comment]
würde einfach die "Must-have"-Funktionalitäten auf Folien bringen und sagen, was wir da gemacht haben. Eventuell noch Screenshots dazu. Fertig. Wir hatten ja schon gutes Feedback bekommen bei unserem Poster.

**Comment by Fasust** [comment]
https://docs.google.com/presentation/d/1sWaOMK1kf6j3-Kr_HB4lsXuYvhgcxyrqX5WbNZVMhK4/edit?usp=sharing
